server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/D3wulf/Bootcamp-ConfigServer
          default-label: main
          search-paths:
          - '*service'